apiVersion: v1
kind: Service
#DNS namnet i klustern som man kan använda.
#Om en annan pod vill nå review-databasen då behöver
#dom connecta till denna hostnamnet : db-booking-service
#
metadata:
  name: db-booking-service
spec:
  #selector kopplar samman dessa med resten av koden som ligger under app: db-booking
  selector:
    app: db-booking
  #anger vilken port dom övriga poddarna ska använda för att koppla till denna service.
  ports:
    - port: 3306
      targetPort: 3306