apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: niklas-bodega-infra-review-service:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: review-service-secret
          ports:
            - containerPort: 8086