apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: niklas-bodega-infra-booking-service:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: booking-service-secret
          ports:
            - containerPort: 8083