apiVersion: v1
kind: Secret
metadata:
  name: db-review-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  MYSQL_DATABASE: ${DB_REVIEW_NAME}
  MYSQL_USER: ${DB_USER}
  MYSQL_PASSWORD: ${DB_PASSWORD}